semana06/dia1/ecommerce/web/urls.py
from django.urls import path

from . import views

app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "categoria/<int:categoria_id>", views.productos_por_categoria, name="categoria"
    ),
    path("marca/<int:marca_id>", views.productos_por_marca, name="marca"),
    path("busqueda", views.producto_por_nombre, name="busqueda"),
    path("producto/<int:producto_id>", views.producto_detalle, name="producto"),
    path("cart", views.carrito, name="carrito"),
    path("cart/add/<int:producto_id>", views.agregar_carrito, name="cart_add"),
    path(
        "cart/del/<int:producto_id>", views.eliminar_producto_carrito, name="cart_del"
    ),
    path("cart/clear", views.limpiar_carrito, name="cart_clear"),
    path("auth/register", views.crear_usuario, name="auth_register"),
    path("cuenta", views.cuenta_usuario, name="cuenta"),
    path("auth/login", views.login_usuario, name="auth_login"),
    path("auth/logout", views.logout_usuario, name="auth_logout"),
    path("cliente/act", views.actualizar_cliente, name="cliente_act"),
    path("pedido", views.pedido, name="pedido"),
    path("pedido/add", views.registrar_pedido, name="pedido_add"),
    path("pago", views.registro_pago, name="pago"),
]

semana06/dia1/ecommerce/web/models.py
from django.db import models


# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=200)

    class Meta:
        db_table = "tbl_categoria"

    def __str__(self):
        return self.nombre


class Marca(models.Model):
    nombre = models.CharField(max_length=200)

    class Meta:
        db_table = "tbl_marca"

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    categoria = models.ForeignKey(Categoria, on_delete=models.RESTRICT)
    marca = models.ForeignKey(Marca, on_delete=models.RESTRICT)
    nombre = models.CharField(max_length=250)
    descripcion = models.TextField(null=True)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    imagen = models.ImageField(upload_to="productos", blank=True)

    class Meta:
        db_table = "tbl_producto"

    def __str__(self):
        return self.nombre


class ProductoImagen(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="galeria", null=True)

    class Meta:
        db_table = "tbl_producto_imagen"
        verbose_name = "Galeria de Fotos"
        verbose_name_plural = "Galeria de Fotos"

    def __str__(self):
        return self.producto.nombre


from django.contrib.auth.models import User


class Cliente(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    dni = models.CharField(max_length=20)
    telefono = models.CharField(max_length=20)
    fecha_nacimiento = models.DateField(null=True)
    direccion = models.TextField()

    class Meta:
        db_table = "tbl_cliente"
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"

    def __str__(self):
        return self.dni


class Pedido(models.Model):
    ESTADO_CHOICES = (("1", "Solicitado"), ("2", "Pagado"))

    cliente = models.ForeignKey(Cliente, on_delete=models.RESTRICT)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    nro_pedido = models.CharField(max_length=20, null=True)
    direccion_envio = models.TextField(null=True)
    payer_id = models.CharField(max_length=200, null=True)
    monto_total = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    estado = models.CharField(max_length=1, default="1", choices=ESTADO_CHOICES)

    class Meta:
        db_table = "tbl_pedido"
        verbose_name = "Pedido"
        verbose_name_plural = "Pedidos"

    def __str__(self):
        return self.nro_pedido


class PedidoDetalle(models.Model):
    pedido = models.ForeignKey(Pedido, on_delete=models.RESTRICT)
    producto = models.ForeignKey(Producto, on_delete=models.RESTRICT)
    cantidad = models.IntegerField(default=1)
    subtotal = models.DecimalField(max_digits=10, decimal_places=2)

    class Meta:
        db_table = "tbl_pedido_detalle"
        verbose_name = "Pedido Detalle"
        verbose_name_plural = "Pedido Detalles"

    def __str__(self):
        return self.producto.nombre

semana06/dia1/ecommerce/web/templates/includes/catalogo/sidebar.html
<aside class="blog-sb-widgets section-sb" id="section-sb">
    <div class="theiaStickySidebar">
        <p class="section-filter-toggle filter_hidden">
            <a href="#" id="section-filter-toggle-btn">Filtrar</a>
        </p>
        <div class="section-filter">
            <div class="section-filter">
                <div class="blog-sb-widget multishopcategories_widget">
                    <h3 class="widgettitle">Categorias</h3>
                    <div class="section-sb-current">
                        <ul class="section-sb-list">
                            {% for categoria in categorias %}
                            <li>
                                <a href="{% url 'web:categoria' categoria.id %}">
                                    <span class="section-sb-label">{{categoria.nombre}}
                                        <span class="count">{{categoria.producto_set.all.count}}</span></span></a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="blog-sb-widget multishopbrands_widget">
                    <h3 class="widgettitle">Marcas</h3>
                    <div class="section-sb-current">
                        <ul class="section-sb-list">
                            {% for marca in marcas %}
                            <li>
                                <a href="{% url 'web:marca' marca.id %}">{{marca.nombre}}
                                    <span class="count">{{marca.producto_set.all.count}}</span></a>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</aside>